version: "3"

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
  adminer:
    image: adminer
    ports:
    - 8081:8080

